version: '1.0'
services:
  server:
    container_name: desafio-STRS
    build: '.'
    volumes:
      - ./:/desafio-STRS
      - ./node_modules:/desafio-STRS/node_modules
    environment:
      - sKEY=123abc
    depends_on:
      - db
    links:
      - db
    ports:
      - '3000:3000'
    restart: on-failure

  db:
    image: 'mongo'
    container_name: mongoDB
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db
    restart: on-failure